Adding SRT files containing English audio subtitles
H-uru/moul-assets pull request #101
Opened 2022-01-16 01:05 UTC by ZarothYe

Start of work for [Plasma feature request #766](https://github.com/H-uru/Plasma/issues/766). Still need to complete the Kirel audio files for Dr. Watson's speech and Tyion's Q4.2021 update. Just wanted to get this in front of people for feedback. I hope to finish up Plasma-side PR in the upcoming week with very crude POC of consuming these files and adding KI chat lines while audio is playing. Fingers crossed...

2022-02-11 20:08 UTC, Hoikas commented
This needs for xKIGUI.max to be updated with the changes to the options menu.

2022-02-11 20:23 UTC, Hazado commented
> This needs for xKIGUI.max to be updated with the changes to the options menu.

Since I have to make changes to this file with #99 , I can upload the changes on my ticket, or create a new one. Up to you Adam.

2022-02-16 02:49 UTC, Hoikas commented
Sorry for the delayed response... But I think this PR is closer to being merged, so I think you should do this one first, then make your cleft changes on top of that. We'll just be sure to merge this PR first. If the subtitle text still needs work, we can pull out the GUI stuff into another commit and accept it before the subtitle contents. Thoughts @ZarothYe?

2022-02-16 03:02 UTC, ZarothYe commented
> Sorry for the delayed response... But I think this PR is closer to being merged, so I think you should do this one first, then make your cleft changes on top of that. We'll just be sure to merge this PR first. If the subtitle text still needs work, we can pull out the GUI stuff into another commit and accept it before the subtitle contents. Thoughts @ZarothYe?

That sounds fine to me. I give my blessing to your suggestion, for whatever it's worth, lol. I'll go ahead and edit my initial PR comment to request merging before #99 .

2022-02-20 10:39 UTC, dgelessus commented
For reference, the updated spellings of the two names in f6ad95420abeeb45919974b84d5df16ae4c88124 come from the Prima guide for Uru ABM. I don't own the guide myself - this was posted in the OpenUru Discord by Zapoteca, who suggested that the Prima transcriptions may be more accurate, because Prima most likely had information directly from Cyan.

To double-check, I listened to how these names are pronounced in the translated voice lines, because presumably all Yeesha voice actresses received the correct spelling. Based on that, I'm relatively sure that the Prima transcriptions are more accurate than previous fan transcriptions. Here's my reasoning copy-pasted from Discord:

> Checking the translated voice lines, here's how the name is pronounced in each language (I hope I got the IPA right):
> 
> * English: [vatuːk]
> * French: [vatuːg]
> * German, Italian: [vaːtʊg]
> * Spanish: [vatuːɣ]
> 
> So the first letter is clearly a "V", there is no "e" at the end, and based on the Spanish pronunciation the last letter is "g" and not "k". From the pronunciation alone, it's difficult to tell how the "u"/"uh"/"oo" should be spelled and if there should be an apostrophe - but based on the other parts, I would assume that the Prima "Va'tuhg" transcription is correct.
> 
> And the second name:
> 
> * English: [tuːɪt]
> * French: [tyɪt] (or possibly [tylɪt])
> * German: [tuːʔɪt]
> * Italian: [tuit]
> * Spanish: [tui]
> 
> Here it's more difficult, because both "Tuit" and "Thu'it" would match these pronunciations well. But the glottal stop in the German version and the slightly weird French pronunciation could come from the apostrophe in "Thu'it", so again I would guess that the Prima transcription is right.

2022-02-23 02:55 UTC, Hoikas commented
Blocking on revisions to xKIGUI.max

2022-03-01 02:25 UTC, Hoikas commented
This PR no longer changes binary assets and is therefore safe to merge alongside H-uru/Plasma#1063.

2022-04-29 18:20 UTC, DamnBriggsy requested changes
Minor errors on inconsistencies with subtitles. Some of these are subjective, take from it what you will!

2022-04-29 18:20 UTC, DamnBriggsy commented on compiled/sfx/clftZandiMinRes01b_eng.sub
> +Zandi: Ok, so... you've got to use that handle in the Cleft to release the windmill brake. Ok?
"Ok" is not the correct spelling and should be "Okay" for consistency with other lines. Acceptable alternatives are "OK" or "O.K.", but the usage should remain consistent throughout.

2022-04-29 18:20 UTC, DamnBriggsy commented on compiled/sfx/krelWatson_eng.sub
> +Dr. Watson: Hello? (tapping mic) Test, test. Victor, are we on? Ok. (clears throat) Ok, then.
s/Ok/Okay/

2022-04-29 18:40 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech01a_eng.sub
> +Yeesha: Cleft. The Fissure in the desert, the wound in the Earth, the path to things beneath the surface.
Hmm, that's an interesting point. I'm not sure which way I think of it. I'd like to get some more perspectives. I took this part directly from the GoA transcript and didn't change the capitalization (https://archive.guildofarchivists.org/wiki/Reference:Yeesha,_bahro_cave_addresses). I tinkered with some punctuation and capitalization in some places for the subtitles based off of the GoA pages, but left a good portion of it alone. I wonder if "Fissure" should not be capitalized either, as it's not the proper-named Star Fissure that she's talking about...

2022-04-29 18:45 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech01a_eng.sub
> +Yeesha: These D'ni people who are now gone came thousands of years ago to the shelter of the cavern to return to Leastness.
Hmm, I'm not hearing it phrased in the speech in the same way you are, I think? I'm hearing it as "These D'ni people" being the subject and the describing phrase "who are now gone" after it.

2022-04-29 18:46 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_TldnSpeech_eng.sub
> +Yeesha: The Least were only animals, after all... (sighs) Animals that could Link.
Hm, yes, I guess the capitalization of the next phrase does indicate the first phrase is a complete sentence. I'll fix this.

2022-04-29 18:53 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_Speech01a_eng.sub
> +Yeesha: Cleft. The Fissure in the desert, the wound in the Earth, the path to things beneath the surface.
I didn't notice that bit about the fissure, I agree with your point here that it should also be lowercase.

2022-04-29 18:53 UTC, ZarothYe commented on compiled/sfx/clftZandiMinRes02b_eng.sub
> +Zandi: C'mon! You gotta push pretty hard on the windmill handle to get it going, all right?
I guess I can change it, but I'm still hearing a "C'mon". Other perspectives welcome. I was trying to keep the vocal flavor of the speech where I could, e.g., "gotta", "gonna".

2022-04-29 18:56 UTC, ZarothYe commented on compiled/sfx/clftZandiMinRes01b_eng.sub
> +Zandi: Ok, so... you've got to use that handle in the Cleft to release the windmill brake. Ok?
Oh, my bad. I did use "Okay" in other places. I'm pretty sure I use "Ok" casually in text personally, so it didn't occur to me to check what is officially correct to use. I might need to check some of the Kirel speeches again.... (ellipsis + period just for you, Briggs 😉 )

2022-04-29 18:57 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_Speech01a_eng.sub
> +Yeesha: These D'ni people who are now gone came thousands of years ago to the shelter of the cavern to return to Leastness.
I was judging this line purely on grammar, it felt more correct to me to be:
"These D'ni people, who are now gone, came thousands of years ago to the shelter..."
You can remove 'who are now gone' and the sentence still works to convey the intended message.

2022-04-29 19:05 UTC, DamnBriggsy commented on compiled/sfx/clftZandiMinRes02b_eng.sub
> +Zandi: C'mon! You gotta push pretty hard on the windmill handle to get it going, all right?
I could go either way on it, very minor quibble.

2022-04-29 19:08 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_GrsnSpeech_eng.sub
> +Yeesha: And yet, it is from within that most nations fall. And so the mighty garrisons of D'ni now stand vacant.
There's no real vocal pause here, but I think this makes sense grammatically. Fair catch.

2022-04-29 19:18 UTC, ZarothYe commented on compiled/sfx/clftYeesha_IntroSp02_eng.sub
> +Yeesha: Have you heard of the city? The deep city, the ancient Uru?
I don't have a strong opinion on this, but I'd like to hear some other people's thoughts.

2022-04-29 19:29 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech02a_eng.sub
> +Yeesha: My humble darkness lasted only a short time before I began to bask in what I could do, what I could write.
I'm unsure. I capitalized "Link", "Art", and "Book" in a some places but I guess this one didn't jump out at me as needing capitalization. According to Alahmnat in discord a while back, they generally go for capitalizing Age, Book (Linking or Descriptive), etc, but that "writing" is a bit more inconsistent. I could go either way.

2022-04-29 19:39 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech01a_eng.sub
> +Yeesha: Cleft. The Fissure in the desert, the wound in the Earth, the path to things beneath the surface.
The more I read this over, the more I agree with you. I'm changing both "fissure" and "earth" to lowercase.

2022-04-29 21:56 UTC, Hoikas reviewed
These comments are only through bhroYeehsa_Speech03a_eng. I am basically thinking that there are a lot of places where commas are being used to indicate pauses in the speech, but the comma is grammatically incorrect. I think an ellipsis is more correct. However, I am no expert on this subject at all.

2022-04-29 21:56 UTC, Hoikas commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The Garden Ages of the proud are beautiful, but they are built on the backs of the Least.
These are both referring to specific groups, so I think capitalization makes sense.

2022-04-29 22:18 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The Garden Ages of the proud are beautiful, but they are built on the backs of the Least.
OK, fixing in Yeesha's Teledahn, Garden, and Gahreesen speeches. These are occurrences where it's clear to me it's talking about a group of people, not a state of emotion or being, unlike "The city grew proud. And then it died." or "I was aware of my power and I was proud." where it's more ambigious. Is that OK?

2022-04-29 23:04 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_KdshSpeech_eng.sub
> +Yeesha: This Kadish you have seen would not give back, would not return, would not let go.
Would periods be better? Make them fractured sentences instead of weird bad-comma phrases?

2022-04-29 23:23 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The Garden Ages of the proud are beautiful, but they are built on the backs of the Least.
Yes, I think those examples there she is just using proud as an adjective. Talking about her pride, their pride, rather than the group "the Proud".

2022-04-29 23:24 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_GrsnSpeech_eng.sub
> +Yeesha: One of the great kings, but yet, he was the maker of the proud. For it was his system of guilds that served as the foundation of power, and corruption.
Agreed

2022-04-29 23:27 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_KdshSpeech_eng.sub
> +Yeesha: This Kadish you have seen would not give back, would not return, would not let go.
My preference would be a semicolon instead of the first comma. 
```suggestion
Yeesha: This Kadish you have seen would not give back; would not return, would not let go.
```
Maybe. I still kind of don't like it, but there's not an easy way to apply exact style rules to speech like this every time.

2022-04-29 23:29 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_Speech02a_eng.sub
> +Yeesha: The D'ni found power in these books, these books you use to travel. They were a gift from the Maker.
This may be a bit out there, but what about a colon?

2022-04-30 00:01 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_Speech03a_eng.sub
> +Yeesha: You return again, return to hear more, return for a third pillar.
```suggestion
Yeesha: You return again. Return to hear more... return for a third pillar.
```

2022-04-30 00:04 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech03a_eng.sub
> +Yeesha: You return again, return to hear more, return for a third pillar.
Yeah, I'd agree with that suggestion, Briggs. Good call.

2022-04-30 00:09 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_KdshSpeech_eng.sub
> +Yeesha: This Kadish you have seen would not give back, would not return, would not let go.
I don't like the semicolon with the still-bad commas. I'd perhaps give them a similar treatment as the last suggestion for a different sentence. `This Kadish you have seen would not give back. Would not return... would not let go.` The second sentence with the ellipse wouldn't technically a proper sentence, but Yeesha plays fast and loose with sentences, honestly.

2022-04-30 14:34 UTC, ZarothYe commented
New commit that consolidates suggestions and attempts to address the remaining comments by @Hoikas and @DamnBriggsy. Please review the latest changes here: https://github.com/H-uru/moul-assets/pull/101/commits/8d115d5cf1dc5e96ef5cdfd598f98076f6fab7ec

Hopefully I fixed stuff and didn't screw any punctuation up further. I didn't address any instances of "write", "writing", or "writer". I'm inclined to leave them lowercase, but I'll adjust if additional people weigh in telling me they should be capitalized.

2022-05-08 21:31 UTC, DurinMephit reviewed
Various nitpicks - nothing critical here.  One question though - why is `clftZandiOpen01a_eng.sub` marked as deleted?

2022-05-08 21:31 UTC, DurinMephit commented on compiled/sfx/krelFanQ42021_eng.sub
> +Tyion: They have their place, and that place is NOT the backroom of the Guild of Messenger's Pub. I mean, this should go without saying, people. Come on.
Corrrected apostrophe placement
```suggestion
Tyion: They have their place, and that place is NOT the backroom of the Guild of Messengers' Pub. I mean, this should go without saying, people. Come on.
```

2022-05-08 21:31 UTC, DurinMephit commented on compiled/sfx/krelWatson_eng.sub
> +Dr. Watson: But let's just say that with your safety uppermost in our minds, we're pushing to approve those Ages just as quickly as we can.
```suggestion
Dr. Watson: But, ooh, uh, let's just say that with your safety uppermost in our minds, we're pushing to approve those Ages just as quickly as we can.
```

2022-05-08 21:31 UTC, DurinMephit commented on compiled/sfx/krelWatson_eng.sub
> +Dr. Watson: We will continue to remove these artifacts if they're found. So far that has proved fruitless.
```suggestion
Dr. Watson: We will continue to remove these artifacts if they're found, but so far that has proved fruitless.
```

2022-05-08 22:30 UTC, ZarothYe commented
> Various nitpicks - nothing critical here. One question though - why is `clftZandiOpen01a_eng.sub` marked as deleted?

That was a small and easily tested sample file that was split out to another PR and merged separately by @Hoikas's request, so it is not included in this batch.

2022-05-08 23:03 UTC, ZarothYe commented
Zandi's opening speech should no longer be missing. Sorry about that; I should have checked my rebase better.

2022-05-09 02:31 UTC, ZarothYe commented on compiled/sfx/krelWatson_eng.sub
> +Dr. Watson: We will continue to remove these artifacts if they're found. So far that has proved fruitless.
Hmm, I wasn't hearing a word here, but after listening again I am hearing a "-t" sound before the "so", so I think you're probably right. I'll adjust this.

2022-05-09 02:34 UTC, ZarothYe commented on compiled/sfx/krelWatson_eng.sub
> +Dr. Watson: But let's just say that with your safety uppermost in our minds, we're pushing to approve those Ages just as quickly as we can.
I think the "ooh" is most likely a cut-off word... probably "we" before he decided to interject the phrase in-between. In this case, I'm thinking that I'll change to something like "But, w-- uh, let's just say [...]".

2022-05-09 02:34 UTC, ZarothYe commented on compiled/sfx/krelFanQ42021_eng.sub
> +Tyion: They have their place, and that place is NOT the backroom of the Guild of Messenger's Pub. I mean, this should go without saying, people. Come on.
Good catch, thanks!

2022-05-09 02:40 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_GrsnSpeech_eng.sub
> +Yeesha: And yet, it is from within that most nations fall. And so, the mighty garrisons of D'ni now stand vacant.
@DamnBriggsy suggested adding the comma after "And so". Both "yet" and "so" are coordinating conjunctions, so I'd think it would make sense to treat the first sentence and the second sentence the same way?

2022-05-09 02:46 UTC, ZarothYe commented on compiled/sfx/clftZandiJC03b_eng.sub
> +Zandi: [whispering]It's in the bedroom... in the Cleft.
I was going a bit more by his tone of voice than the volume. He's giving off sort of *leaning in conspiratorially to tell you a secret* vibes in this clip to me. I'll add the space for readability, though. That makes sense.

2022-05-09 02:54 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The lives in those Ages were consumed, and the D'ni gave nothing back.
I think these are two independent clauses, so wouldn't it be appropriate to have a comma here?

2022-05-09 16:49 UTC, DurinMephit commented on compiled/sfx/bhroYeesha_GrsnSpeech_eng.sub
> +Yeesha: And yet, it is from within that most nations fall. And so, the mighty garrisons of D'ni now stand vacant.
Doesn't matter to me, same explanation as prior item.  A comma is fine here if folks prefer it, I'm only saying it's not strictly necessary.

2022-05-09 21:31 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The ancient tales of Thu'it's Ocean or, of course, the story of King Shomat and his brothers, which even speaks of gardens and death.
I've pondered this one for a while. I'm fairly certain there needs to be a pair of commas surrounding the "of course", since it is a nonessential phrase. The main sentence (which isn't even complete, as there's no verb present) is `The ancient tales of Thu'it's Ocean or the story of King Shomat and his brothers`. I'm not entirely convinced that a comma should go before the `or` here... as these are not independent clauses (IMO, at least, since they don't even have verbs). If we treat it as a list, it only consists of two items total and doesn't need a comma.

I think the possible options are:
1. `The ancient tales of Thu'it's Ocean or, of course, the story of King Shomat and his brothers [...]`
2. `The ancient tales of Thu'it's Ocean, or, of course, the story of King Shomat and his brothers [...]`

My preference would be for the first option -- which is how it is currently written.

2022-05-09 21:36 UTC, dpogue commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The ancient tales of Thu'it's Ocean or, of course, the story of King Shomat and his brothers, which even speaks of gardens and death.
Maybe dashes? I'm not sure it's any more readable 😕 

> The ancient tales of Thu'it's Ocean, or — of course — the story of King Shomat and his brothers [...]

2022-05-10 00:51 UTC, Hoikas commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The lives in those Ages were consumed, and the D'ni gave nothing back.
A comma is needed here because this is a compound sentence. Those take the form of `<subject> <verb>, (and|or|but) <subject> <verb>`.

2022-05-10 00:52 UTC, Hoikas commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The ancient tales of Thu'it's Ocean or, of course, the story of King Shomat and his brothers, which even speaks of gardens and death.
This speech is a complete disaster by Yeesha. Good luck!

2022-05-10 09:50 UTC, Deledrius commented on compiled/sfx/krelWatson_eng.sub
> +Dr. Watson: We will continue to remove these artifacts if they're found. So far that has proved fruitless.
I'm not sure I'll ever understand it.  Having him use the same "voice" led me to assume it was Zandi the first time I encountered this speech in my initial play-through.

2022-05-10 12:03 UTC, DamnBriggsy commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The ancient tales of Thu'it's Ocean or, of course, the story of King Shomat and his brothers, which even speaks of gardens and death.
My thought is the second option, `Ocean, or, of course`, is more correct. I fully agree this speech is a disaster.

2022-05-10 13:13 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_GrdnSpeech_eng.sub
> +Yeesha: The ancient tales of Thu'it's Ocean or, of course, the story of King Shomat and his brothers, which even speaks of gardens and death.
> My thought is the second option, `Ocean, or, of course,`, is more correct. I fully agree this speech is a disaster.

All right, since most seem to agree that the additional comma is better, I'll add it. So let it be written. So let it be done! 😉

2022-05-16 00:29 UTC, Hoikas approved these changes
Let's rock with this initial load - I think we can continue to make adjustments down the road, if needed.

2022-05-16 21:20 UTC, merged