Add French subtitles
H-uru/moul-assets pull request #179
Opened 2022-10-08 21:29 UTC by ZarothYe

Transcriptions of Yeesha speeches courtesy of mystpedia.net, a French-based Myst resource website. Transcriptions of Zandi's speeches and the Kirel Watson speech to be provided by skyisblu in the near future.

Sectioning, timings, and some capitalization (to match capitalization of Journey, Least, Proud, etc. in English) done by me.

2022-10-09 16:36 UTC, ZarothYe commented
Marking as ready for review since draft PRs don't count for Hacktoberfest, apparently. ;) Feel free to comment or request changes for the available speeches. I will add the Zandi and Watson speeches as soon as I can. Thanks!

2022-10-13 21:00 UTC, dgelessus requested changes
I'm not a native speaker, so take this with a grain of salt (though I did check a dictionary where I was unsure).

I checked the spelling of the text and that it matches the audio, but I haven't checked any of the timings.

2022-10-14 19:39 UTC, skyisbluu commented on compiled/sfx/tmnaYeesha_FinalSp01_fre.sub
> +Yeesha: Puis vous avez pris le chemins du retour. Vous avez rendu les piliers et maintenant un Bahro, le plus Humble, est retourné à D'ni.
Sorry, my bad - chemin does not have an "s".

2022-10-14 19:43 UTC, skyisbluu commented on compiled/sfx/bhroYeesha_Speech02b_fre.sub
> +Yeesha: Le Bahro reviendra. Ces pilliers sont notre Voyage. Le retour des pilliers est le retour du Bahro.
Only one "l" in piliers.

2022-10-14 19:44 UTC, skyisbluu commented on compiled/sfx/bhroYeesha_Speech03a_fre.sub
> +Yeesha: Vous revenez encore, vous revenez pour en apprendre plus, vous revenez pour un troisième pillier.
Only one "l" in pilier.

2022-10-14 20:17 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech03a_fre.sub
> +Yeesha: Vous revenez encore, vous revenez pour en apprendre plus, vous revenez pour un troisième pillier.
I think all instances of pillier were corrected in f704b7edacdef5a5835273fc7234797b0926c197. :)

2022-10-14 20:17 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech02b_fre.sub
> +Yeesha: Le Bahro reviendra. Ces pilliers sont notre Voyage. Le retour des pilliers est le retour du Bahro.
I think all instances of pillier were corrected in f704b7edacdef5a5835273fc7234797b0926c197. :)

2022-10-14 20:26 UTC, ZarothYe commented on compiled/sfx/tmnaYeesha_FinalSp01_fre.sub
> +Yeesha: Puis vous avez pris le chemins du retour. Vous avez rendu les piliers et maintenant un Bahro, le plus Humble, est retourné à D'ni.
Corrected in 2e4b95df0690ccb8ed72a143f717a560a6dcd95e! Thanks! :)

2022-10-17 04:37 UTC, ZarothYe commented
Zandi's speeches and Watson's Kirel speech have now been added and are ready for review. No more additions are expected.

2022-10-17 16:03 UTC, skyisbluu requested changes

2022-10-17 16:03 UTC, skyisbluu commented on compiled/sfx/krelWatson_fre.sub
> +Dr. Watson: Par conséquent, les inspections de sécurité n'ont pas été misent en place dans ces zones. Soyez vigilants -- je ne le repèterai jamais assez, ces pierres de liaison n'ont pas été approuvé
```suggestion
Dr. Watson: Par conséquent, les inspections de sécurité n'ont pas été misent en place dans ces zones. Soyez vigilants -- je ne le répéterai jamais assez, ces pierres de liaison n'ont pas été approuvées par le CRD et, du coup, nous ne garantissons pas votre sécurité.
```

2022-10-17 16:03 UTC, skyisbluu commented on compiled/sfx/krelWatson_fre.sub
> +Dr. Watson: Utilisez-les à vos risques et perils !
```suggestion
Dr. Watson: Utilisez-les à vos risques et périls !
```

2022-10-17 16:03 UTC, skyisbluu commented on compiled/sfx/krelWatson_fre.sub
> +Dr. Watson: Pour tous les autres, merci de votre attention. Nous esperons que vous passerez un bon séjour ici. Oh ! Euh ! J'oubliais -- amusez-vous bien.
```suggestion
Dr. Watson: Pour tous les autres, merci de votre attention. Nous espérons que vous passerez un bon séjour ici. Oh ! Euh ! J'oubliais -- amusez-vous bien.
```

2022-10-17 17:52 UTC, skyisbluu requested changes

2022-10-17 17:52 UTC, skyisbluu commented on compiled/sfx/tmnaYeesha_FinalSp01_fre.sub
> +Yeesha: La cité des profondeurs respire. C'est un nouveau uru.
This is the second instance of the mention of URU - I am wondering if it should be capitalized? As in Uru, maybe?

2022-10-17 17:52 UTC, skyisbluu commented on compiled/sfx/clftYeesha_IntroSp02_fre.sub
> +Yeesha: Avez-vous entendu parler de la ville des profondeurs, l'ancienne uru ?
Mention of URU - should this not be capitalized to Uru, perhaps?

2022-10-18 04:28 UTC, ZarothYe commented on compiled/sfx/bhroYeesha_Speech01a_fre.sub
> +et revenir à un mode de vie plus Humble.
Ah, yikes. Yes it should -- I'll fix that. Good catch!

2022-10-18 04:58 UTC, ZarothYe commented on compiled/sfx/tmnaYeesha_FinalSp01_fre.sub
> +Yeesha: La cité des profondeurs respire. C'est un nouveau uru.
I believe in the English subtitles I made it lowercase in response to this comment https://github.com/H-uru/moul-assets/pull/101/commits/53013849a50386b96703313729121f4521af297e#r862025776 so I was trying to be consistent. I didn't have a strong opinion or sense of whether Yeesha was referring to a proper name or special noun (like Age or Least) here. I don't think there was much engagement in the related conversation back in April, but I'd be very happy to listen to discussion if anyone else has thoughts and to change it in the French and English subtitles if needed. :)

2022-10-19 00:32 UTC, ZarothYe commented on compiled/sfx/tmnaYeesha_FinalSp01_fre.sub
> +Yeesha: La cité des profondeurs respire. C'est un nouveau uru.
Was informed that the link to the earlier English subtitle PR didn't work. Here's a screenshot of the (short) discussion. Like I said... no other thoughts were given back then that I remember or could find.
![image](https://user-images.githubusercontent.com/94947971/196569805-b98ce18d-aba8-4b5e-9d13-959f8895fb6d.png)

2022-10-19 00:51 UTC, Deledrius commented on compiled/sfx/tmnaYeesha_FinalSp01_fre.sub
> +Yeesha: La cité des profondeurs respire. C'est un nouveau uru.
That's an excellent question.  Honestly, I feel like the ambiguity is intentional, but the only way to know for certain would be to ask the authors. :(

2022-10-19 12:51 UTC, skyisbluu commented on compiled/sfx/tmnaYeesha_FinalSp01_fre.sub
> +Yeesha: La cité des profondeurs respire. C'est un nouveau uru.
Yeah, this does makes sense - the only reason I suggested capitalization was because I didn't recognize the word outside the game's usage, and a quick internet search at the time gave me nothing.

2022-11-12 21:24 UTC, Hoikas commented
Is this good to go?

2022-11-13 03:56 UTC, skyisbluu commented
I think so, but I leave the final word to Zaroth.

2022-11-13 06:01 UTC, ZarothYe commented
Since the ambiguity around the capitalization of "uru" has not been cleared up and no one has made any other comments or requests... I think this is complete, yes.

2022-11-13 15:37 UTC, merged