French Uru credits in alignment with English contents
H-uru/moul-assets pull request #180
Opened 2022-10-14 05:01 UTC by ZarothYe

This PR brings the French credits journal contents (previously copied from Uru:CC credits, I believe) into alignment with the MOUL Uru credits that we have in English. I welcome any feedback on any French that needs to be adjusted. I made my best guesses based on existing CC credit contents for wording on titles/roles along with a sprinkling of Google Translate. There are still a few snippets in the Licences Open Source section that are in English if anyone wants to take a crack at writing those in French. I felt highly underqualified to try those myself. ;)

This PR also fix very minor spacing abnormalities in the English credits.

Videos of the results in-game.

English:

https://user-images.githubusercontent.com/94947971/195764911-b54d0f71-199d-4b72-b0c7-311805fd855c.mp4

French:

https://user-images.githubusercontent.com/94947971/195764960-bc07ad28-6485-4106-9159-4268d8c6bd55.mp4

2022-10-14 19:33 UTC, skyisbluu requested changes

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +<p align=left>Randy Ridgway<p align=right>Programmeur physiques
I think this should be Programmeur physique, no "s"

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +<font size=26><p align=center>Conception et commandes<font spacing=-5>
I believe control in this case might be better translated to "contrôle".

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +<p align=left>Dave Smith<p align=right>Responsable du informatique
Should be "Responsable de l'informatique"

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +<font size=26 spacing=-18><p align=center>Acteurs voix<font spacing=-5>
Voice actor is "Doubleur", or more elegantly "Artistes Vocal"

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +This software is based in part on the work of the Independent JPEG Group.
Ce logiciel est basé en partie sur le travail de l'Independent JPEG Group.

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/)
Ce produit inclut un logiciel développé par le OpenSSL Project pour une utilisation dans OpenSSL Toolkit

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +This product includes cryptographic software written by Eric Young (eay@cryptsoft.com).
Ce produit comprend un logiciel cryptographique écrit par Eric Young

2022-10-14 19:33 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +This product includes software written by Tim  Hudson (tjh@cryptsoft.com).
Ce produit comprend un logiciel écrit par Tim Hudson

2022-10-14 20:44 UTC, dgelessus commented
> There are still a few snippets in the Licences Open Source section that are in English if anyone wants to take a crack at writing those in French.

Hmm, I wonder if the license/attribution bits should be translated at all? Because for example the SSLeay license says:

> 3. All advertising materials mentioning features or use of this software must display the following acknowledgement:
>    "This product includes cryptographic software written by Eric Young (eay@cryptsoft.com)"
>    The word 'cryptographic' can be left out if the rouines from the library being used are not cryptographic related :-).

I'm not a lawyer obviously, but since the license asks for this specific sentence, I feel like it would be safer to leave it untranslated..

2022-10-16 23:37 UTC, Hoikas commented
> > There are still a few snippets in the Licences Open Source section that are in English if anyone wants to take a crack at writing those in French.
> 
> Hmm, I wonder if the license/attribution bits should be translated at all? Because for example the SSLeay license says:
> 
> > 3. All advertising materials mentioning features or use of this software must display the following acknowledgement:
> >    "This product includes cryptographic software written by Eric Young ([eay@cryptsoft.com](mailto:eay@cryptsoft.com))"
> >    The word 'cryptographic' can be left out if the rouines from the library being used are not cryptographic related :-).
> 
> I'm not a lawyer obviously, but since the license asks for this specific sentence, I feel like it would be safer to leave it untranslated.

I had the same reaction initially, but I am leaning more toward wanting the notice to be translated for each individual localization. The credits here are a user friendly listing and do not necessarily represent the end-all-be-all of open source licenses. Ideally, we keep them up to date, but it's definitely a manually curated process. We really should have an untranslated definitive list of library credits produced using eg vcpkg's `share/{$PORT}/copyright` files lying in the game directory, which would contain the complete and unadulterated list of credits. That's, of course, outside the scope of this PR.

I'd appreciate comments from other maintainers on this.

2022-10-17 04:56 UTC, ZarothYe commented
New French preview with the updates and new translations from sky included :)

https://user-images.githubusercontent.com/94947971/196092275-62c8154b-a6e6-4d9d-8c34-41444dc16bc6.mp4

2022-10-17 05:01 UTC, dpogue commented
Merci Zaroth et Skyisblu pour vos efforts ici! 🙇🏼‍♂️

2022-10-17 18:47 UTC, skyisbluu requested changes

2022-10-17 18:47 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +<font size=24 spacing=-10><p align=left>Mark H. DeForest<p align=right>CTO
CTO in French is a Directeur de la Technologie, or Directeur Technique

2022-10-17 18:47 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +<p align=left>Eliza Wyatt<p align=right>Testeuse
```suggestion
<p align=left>Bradford Chapman<p align=right>Testeur AQ
<p align=left>John Taitingfong<p align=right>Testeur AQ
<p align=left>Eliza Wyatt<p align=right>Testeuse AQ
```

2022-10-17 18:47 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
>  <p align=left>Friends of Sironka Dance Troupe<p align=right>Choeurs
```suggestion
<p align=left>Friends of Sironka Dance Troupe<p align=right>Chanteurs
```

2022-10-17 18:47 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
>  <p align=left>Tasha Koontz<p align=right>Voix
```suggestion
<p align=left>Tasha Koontz<p align=right>Chanteuse
```

2022-10-17 18:47 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
> +<pb><font size=26><p align=center>Un Merci Spécial à<font spacing=-5>
```suggestion
<pb><font size=26><p align=center>Remerciement Spécial à<font spacing=-5>
```

2022-10-17 18:47 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
>  Certains sons et certains enregistrements vocaux sont fournis par The Friends of Sironka Dance Troupe, sous licence non-exclusive de Cyan, utilisé avec leur autorisation.
```suggestion
Certains sons et enregistrements vocaux sont fournis par The Friends of Sironka Dance Troupe, sous licence nonexclusive de Cyan, utilisé avec leur autorisation.
```

2022-10-17 18:47 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
>  <font size=24 spacing=-10><p align=center>Artbeats Digital Film Library
```suggestion
<font size=24 spacing=-10><p align=center>Bibliothèque de films numériques Artbeats
```

2022-10-18 04:21 UTC, ZarothYe commented on compiled/dat/GlobalFrench.loc
> +<font size=24 spacing=-10><p align=left>Mark H. DeForest<p align=right>CTO
I checked in-game and "Directeur de la Technologie" will fit properly, so I'll go with that.

2022-10-18 04:24 UTC, ZarothYe commented on compiled/dat/GlobalFrench.loc
>  <font size=24 spacing=-10><p align=center>Artbeats Digital Film Library
I'm not entirely certain if this should be translated. 🤔 This felt more like a proper name of a project or group, similar to "The Friends of Sironka Dance Group" or "The Web M Project". I don't really know much about Artbeats, though, so I could be wrong. Can anyone else weigh in with their thoughts, please?

2022-10-18 15:58 UTC, skyisbluu commented on compiled/dat/GlobalFrench.loc
>  <font size=24 spacing=-10><p align=center>Artbeats Digital Film Library
Checked it out - Artbeats is a company that supplies stock footage for use on many different platforms, including Adobe, gettyimages, shutterstock, so the phrase is descriptive of the digital film library itself, not part of the proper name. I think this translation should be ok :)

2022-10-19 00:13 UTC, Hoikas commented on compiled/dat/GlobalFrench.loc
>  <font size=24 spacing=-10><p align=center>Artbeats Digital Film Library
I would leave the name of the company (Artbeats) untranslated but translate the specific resource being cited.

2022-11-12 21:24 UTC, Hoikas commented
Is this good to go?

2022-11-13 03:57 UTC, skyisbluu commented
Yes, I believe there's nothing more to translate, but I leave the final word to Zaroth.

2022-11-13 06:26 UTC, ZarothYe commented
It's complete as far as I'm concerned.

2022-11-13 15:37 UTC, merged