Fan Relto video to replace Yeesha intro
H-uru/moul-assets pull request #218
Opened 2023-02-07 17:19 UTC by Hazado

Fan Video designed to replace the Yeesha Intro played when you first arrive in Relto age

Voice Overs done by
English - Maurus
French - Skyisblu
German - Taliana

Included the Higher Quality version in the source files

The webm version was done with quality settings of 31 in Handbrake

2023-02-07 18:48 UTC, DoobesURU commented
Yay! Glad it's finally ready to go. At some point, we'll need to get a couple of people to do the Italian and Spanish dubs too. 😉

2023-03-07 04:16 UTC, Hoikas requested changes
`sources/avi/Relto23IntroEngFreGerFinal.mkv` is not checked into git lfs. Please strip off the last commit, add the line `*.mkv filter=lfs diff=lfs merge=lfs -text` to .gitattributes, then recommit `sources/avi/Relto23IntroEngFreGerFinal.mkv`.

2023-03-07 04:46 UTC, Hazado commented
should be fixed now

2023-03-07 23:53 UTC, Hoikas approved these changes

2023-04-12 23:10 UTC, merged