Add instructions for browsing using LFS cloning
H-uru/moul-assets pull request #223
Opened 2023-02-21 02:02 UTC by bertvandepoel

Based on #222 there was a need for this. Not sure if the "git lfs clone" is the best option, or if it would be better to just go for a "one time git lfs install", so feedback is very welcome!

2023-02-21 04:21 UTC, dpogue commented on README.md
> +You may notice while browsing this repository online or after cloning on your own machine that most files seem to be small text files containing some kind of hash reference. This is because the MOUL
> You can of course also enable Git LFS be default.

This should say "**by** default", and we might also want to drop the "of course"

2023-02-21 11:39 UTC, Deledrius requested changes

2023-02-21 11:39 UTC, Deledrius commented on README.md
> +You may notice while browsing this repository online or after cloning on your own machine that most files seem to be small text files containing some kind of hash reference. This is because the MOUL
```suggestion
You may notice while browsing this repository online or after cloning on your own machine that most files seem to be small text files containing some kind of hash reference. This is because the MOUL assets repository is too large for (free) GitHub. We therefore use an external Git Large File Storage server. The easiest way to download the entire repository is to use `git lfs clone`. Do keep in mind that the repository is very large (over 20GB), so make sure to run this command in a location with sufficient space. You may also choose to enable Git LFS by default. You can find some basic information on the [Git LFS website](https://git-lfs.com/) or refer to the [Git LFS wiki page on pulling and cloning](https://github.com/git-lfs/git-lfs/wiki/Tutorial#pulling-and-cloning).
```

2023-02-21 12:11 UTC, Deledrius commented
According to the docs (and in my own testing), it appears that the `git lfs clone` command is unnecessary once git-lfs is installed.  On Windows, git-lfs is installed by default with git-for-windows, but generally needs to be installed as its own package on Linux and macOS (instructions are provided in the linked documentation).  Once that's done, a normal `git clone` appears to work as expected against a repository with LFS data.

2024-11-14 23:51 UTC, Hoikas approved these changes

2024-11-14 23:51 UTC, merged